export const SIZES = [
  {
    id: "instagram-post",
    nameAr: "منشور إنستغرام",
    nameEn: "Instagram Post",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    platform: "Instagram",
  },
  {
    id: "whatsapp-image",
    nameAr: "صورة واتساب",
    nameEn: "WhatsApp Image",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    platform: "WhatsApp",
  },
  {
    id: "instagram-story",
    nameAr: "ستوري إنستغرام",
    nameEn: "Instagram Story",
    width: 1080,
    height: 1920,
    ratio: "9:16",
    platform: "Instagram",
  },
  {
    id: "tiktok",
    nameAr: "تيك توك",
    nameEn: "TikTok",
    width: 1080,
    height: 1920,
    ratio: "9:16",
    platform: "TikTok",
  },
  {
    id: "snapchat",
    nameAr: "سناب شات",
    nameEn: "Snapchat",
    width: 1080,
    height: 1920,
    ratio: "9:16",
    platform: "Snapchat",
  },
  {
    id: "whatsapp-status",
    nameAr: "ستاتس واتساب",
    nameEn: "WhatsApp Status",
    width: 1080,
    height: 1920,
    ratio: "9:16",
    platform: "WhatsApp",
  },
  {
    id: "instagram-portrait",
    nameAr: "منشور طولي إنستغرام",
    nameEn: "Instagram Portrait",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    platform: "Instagram",
  },
  {
    id: "tiktok-thumb",
    nameAr: "صورة مصغرة تيك توك",
    nameEn: "TikTok Thumbnail",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    platform: "TikTok",
  },
  {
    id: "twitter-banner",
    nameAr: "غلاف تويتر",
    nameEn: "Twitter Banner",
    width: 1500,
    height: 500,
    ratio: "16:9",
    platform: "Twitter/X",
  },
  {
    id: "youtube-thumb",
    nameAr: "صورة مصغرة يوتيوب",
    nameEn: "YouTube Thumbnail",
    width: 1280,
    height: 720,
    ratio: "16:9",
    platform: "YouTube",
  },
  {
    id: "facebook-cover",
    nameAr: "غلاف فيسبوك",
    nameEn: "Facebook Cover",
    width: 820,
    height: 312,
    ratio: "Wide",
    platform: "Facebook",
  },
  {
    id: "linkedin-banner",
    nameAr: "غلاف لينكدإن",
    nameEn: "LinkedIn Banner",
    width: 1584,
    height: 396,
    ratio: "Wide",
    platform: "LinkedIn",
  },
  {
    id: "linkedin-post",
    nameAr: "منشور لينكدإن",
    nameEn: "LinkedIn Post",
    width: 1200,
    height: 627,
    ratio: "Other",
    platform: "LinkedIn",
  },
  {
    id: "business-card",
    nameAr: "بطاقة عمل",
    nameEn: "Business Card",
    width: 1050,
    height: 600,
    ratio: "Other",
    platform: "General",
  },
  {
    id: "custom",
    nameAr: "مخصص",
    nameEn: "Custom",
    width: 1080,
    height: 1080,
    ratio: "Other",
    platform: "Custom",
    isCustom: true,
  },
];

export const RATIO_GROUPS = ["1:1", "9:16", "4:5", "16:9", "Wide", "Other"];